### ISSUE TITLE
1.9.1 compatibility 

### ISSUE THREAD

**Issue by frankoostrum** [jayelkaake/enhancedgrid#13]
Installing via modman results in a blank manage products page.
(even after a cache clean, reindexall and an admin logout/login)

**Comment by Insect2015** [comment]
Hello jayelkaake,

Can you please gif a update I want to use the extension for Magento 1.9.2.1.

best regards,
Michel

**Comment by jayelkaake** [comment]
@Insect2015 , you running into the same issue? I think it works for me fine with modman, but I could be missing something. I added a new modman recently.

**Comment by ruuter** [comment]
I'm still having same issue, blank page. 
Magento 1.9.2.1 with both `v1.3.2.2` and current `dev-master`. Installed with composer. **var/log/system.log** says:
`CRIT (2): Not valid template file:adminhtml/default/default/template/tbt/enhancedgrid/catalog/product.phtml`

**Comment by jayelkaake** [comment]
That means your template file is missing. Can you try re-installing?

**Comment by ruuter** [comment]
File is not missing. It does exists. Just in case I did re-install it, but still blank page.

**Comment by jayelkaake** [comment]
Are you using mod man?

**Comment by ruuter** [comment]
I'm using [Magento Composer Installer] (https://github.com/Cotya/magento-composer-installer)

**Comment by jayelkaake** [comment]
Hmm.. Are you using symlinks and if so do you have sym links allowed in
your config?

Jay

**Comment by ruuter** [comment]
Oh, Yes, just figured it out myself also. My bad. I'm using symlinks and they were not allowed.
All good now. Thanks a lot for fast support :)

**Comment by ruuter** [comment]
For anyone stumbling upon this here with same issue:
System > Configuration > Developer > Template Settings > Allow Symlinks
or do not use symlinks with Composer Installer by adding following to your composer.json `extra` block:
`"magento-deploystrategy":"copy"`

**Comment by jayelkaake** [comment]
Glad you got it working, np!

Jay
