### ISSUE TITLE
v1.3.4.1 - Manage products list shows up twice

### ISSUE THREAD

**Issue by m-overlund** [jayelkaake/enhancedgrid#16]
After upgrading to 1.3.4.1 product list now shows up twice, beneath each other.

![magento admin](https://cloud.githubusercontent.com/assets/504236/10879725/1654c188-8156-11e5-968e-76cf8ab8a3de.png)

**Comment by sergeifilippov** [comment]
Confirmed for me also.

Magento 1.9.0.1

**Comment by CedricLeong** [comment]
remove 

 $this->_addContent(
            $this->getLayout()->createBlock('enhancedgrid/catalog_product')
        );

from the index action of the controller

**Comment by sergeifilippov** [comment]
PR added https://github.com/jayelkaake/enhancedgrid/pull/17

Thanks to  @CedricLeong :+1:

**Comment by jayelkaake** [comment]
Sorry about that and thanks for the PR @sergeifilippov !!!

**Comment by sergeifilippov** [comment]
Thanks to @CedricLeong :+1: :+1: for actually providing the fix. :)
