### ISSUE TITLE
Product filters

### ISSUE THREAD

**Issue by valguss** [jayelkaake/enhancedgrid#19]
I've just updated the module to the latest version and I have a bit of an issue. When filtering products, I loose my custom defined columns, and no filtering occurs.
However, if I refresh the page, the custom columns come back and the also shows only the filtered products.
Feels like the AJAX grid isen't hitting the correct route or something like it.

Any ideas?

**Comment by jayelkaake** [comment]
Yeah that means that the config is not up-to-date.
Did you clear config and layout cache after the update? If you didn't then what you've described would happen.
Also, what version are you running?

**Comment by valguss** [comment]
I've literally just re-installed with the latest version and cleared caches. I'll give it another go

**Comment by valguss** [comment]
Sorry, stepped through the code and discovered a rewrite conflict for the admin controller.
