### ISSUE TITLE
Blank Product Page

### ISSUE THREAD

**Issue by dwhiting10** [jayelkaake/enhancedgrid#20]
After installing the SUPEE-6788 patch the the version of Enhanced Grid (v1.3.2.1 from Magento Connect) would show a 404 page when I went to view the product grid.  So I came here and grabbed the latest version of Enhanced Grid (v1.3.4.1).  I uninstalled the old version and then installed v1.3.4.1.  Now when I try and open the product grid page it no longer show a 404 page but the place where the product grid should be is blank.  I don't see any js console errors or PHP errors (I have php errors turned on).  See screenshot: http://prntscr.com/92o7u0  I have the * next to the Manage Products link and the url looks like this: https://mysite/index.php/admin/catalog_product/....  The site is Magento v1.9.1.0  Any idea why I am seeing the blank page instead of the product grid?

**Comment by jayelkaake** [comment]
Hey sorry for the late response.

The magento Connect version was outdated because I no longer had access to the account that held the page. I was restored access recently and just updated it there. Feel free to try installing again and it will work, sorry for the trouble!

**Comment by dwhiting10** [comment]
Thanks.  I installed the latest version from Magento Connect (v1.031) cleared the cache, logged out and logged back in.  The product page loads ok in the admin but didn't seem to be "enhanced"  (the * was also missing next to the product page name in the admin menu).  So I went to System ->Configuration to see if I needed make some changes to the config but I am seeing this error:  _Fatal error: Call to undefined method Mage_Eav_Model_Resource_Entity_Attribute_Collection::addVisibleFilter() in /public_html/app/code/community/TBT/Enhancedgrid/Model/System/Config/Source/Columns/Show.php on line 10_

**Comment by jayelkaake** [comment]
Hmm that's the super old version from Magento 1.2 lol... I think they're
still approving the submission or something, I'll check it today.

Can you just install with the github repo or modman or composer?

Jay

**Comment by dwhiting10** [comment]
Thanks I just tried that but I am still seeing a blank product page.   I grabbed the master version of Enhanced Grid and installed it via FTP.  Cleared the cache, re-indexed logged out and logged back but the product page is still blank with no errors.  I tried enabled/disabling the new Admin routing compatibility mode for extensions setting in Configuration but still nothing.

**Comment by jayelkaake** [comment]
Hmm... something is going on for you. It's possible that you have a conflicting extension... did you check to make sure you don't have module output disabled in System -> Config -> Advanced?

**Comment by dwhiting10** [comment]
Wow thanks that was the problem.  When it first stopped working I had disabled it in Config -> Advanced to try and make the product area usable again until I could update the module.    I completely forgot that I had done that so I forgot to re-enable it once I had completed the update.  Thanks for all your help :smile:

**Comment by jayelkaake** [comment]
Haha oops! Well glad you got it working.

Jay
