### ISSUE TITLE
404 error on Products page

### ISSUE THREAD

**Issue by tomlankhorst** [jayelkaake/enhancedgrid#21]
Installed (modman) plugin. Asterix does appear after products entry in main menu. 404 Error on the products page from an URL of https://www.sweettoothrewards.com/. 

In my case: https://www.sweettoothrewards.com/m/?data=7b2261223a22656e68616e63656467726964222c22762.......

**Comment by jayelkaake** [comment]
This should now be fixed. Try updating to v1.3.4.3 - sorry about that!
