### ISSUE TITLE
1.9.2.1 - 1.9.2.2 massRefresh don't work

### ISSUE THREAD

**Issue by karol-gontarski** [jayelkaake/enhancedgrid#23]
1.9.2.1 - 1.9.2.2 massRefresh don't work

**Comment by jayelkaake** [comment]
Out of curiosity, what are you using the mass refresh for? I was going to remove that option. It used to be used to load and save products back when Magento was newer and wasn't always populating data properly without doing a save()

**Comment by karol-gontarski** [comment]
just to be :) I repaired it I'm also add mass attribute set change option

**Comment by jayelkaake** [comment]
Can you submit a PR?

:)
J

**Comment by karol-gontarski** [comment]
np in few days ...

2015-12-24 2:08 GMT+01:00 Jay El-Kaake <notifications@github.com>:

**Comment by jayelkaake** [comment]
That would be awesome, thanks!!

Jay

**Comment by karol-gontarski** [comment]
fixed in ~~#24~~ #26
