### ISSUE TITLE
Ajax-Loader broken in 1.9.2.2

### ISSUE THREAD

**Issue by damac23** [jayelkaake/enhancedgrid#25]
Hi,

the first page does contain the new columns, but if I use the paginate so change to page 2 the additional columns and the "Export to"-function are gone - after reloading the page it's all back again :)

thanks
Klaus

**Comment by jayelkaake** [comment]
Hmm let me test his out and get back to you...

**Comment by pquerner** [comment]
I cannot confirm this. It works just fine when I hit the "next" (or "prev" button) or even enter a page number in and hit enter.

**Comment by jayelkaake** [comment]
Thanks @pquerner !!
