### ISSUE TITLE
Fix for 1.8 Compatibility

### ISSUE THREAD

**Issue by jonpday** [jayelkaake/enhancedgrid#3]
Hi, 

The following patch will make the module compatible with 1.8, are you interested in receiving a pull request and publishing the updated version on Magento Connect? I haven't tested the update on older versions but will do if you are planning to publish the update...

Thanks,
JD

    commit 24bc23405f70456c5ccbee92f381f5d0500724bf
    Author: Jonathan Day <jonathan@aligent.com.au>
    Date:   Mon Oct 7 11:55:37 2013 +1030

    resolve 1.8 compatibility issue for TBT_EnhancedGrid

    diff --git a/app/code/community/TBT/Enhancedgrid/Block/Catalog/Product/Grid.php b/app/code/community/TBT/Enhancedgrid/Block/Catalog/Produ
    index ad81983..2ba0953 100644
    --- a/app/code/community/TBT/Enhancedgrid/Block/Catalog/Product/Grid.php
    +++ b/app/code/community/TBT/Enhancedgrid/Block/Catalog/Product/Grid.php
    @@ -647,16 +647,16 @@ class TBT_Enhancedgrid_Block_Catalog_Product_Grid extends Mage_Adminhtml_Block_W
            $collection 
                ->joinField('categories',
                    $ccev_t,
    -                   'GROUP_CONCAT(_table_categories.value)',
    +                   'GROUP_CONCAT(DISTINCT at_categories.value)',
                    'entity_id=category_id',
    -                   "_table_categories.attribute_id={$category_name_attribute_id}",
    +                   "at_categories.attribute_id={$category_name_attribute_id}",
                    'left');
            $collection 
                ->joinField('category',
                    $ccev_t,
                    'value',
                    'entity_id=category_id',
    -                   "_table_category.attribute_id={$category_name_attribute_id}",
    +                   "at_category.attribute_id={$category_name_attribute_id}",
                    'left');
            $collection->groupByAttribute('entity_id');

**Comment by jayelkaake** [comment]
Hey @jonpday, almost 3 years later I'm only now responding! Sorry!!
If you still want, you can submit a PR and I'll merge. Just make sure it also works with older versions of Enhancegrid please :)
