### ISSUE TITLE
Category column

### ISSUE THREAD

**Issue by melaxon** [jayelkaake/enhancedgrid#37]
Please check this screenshot
https://gyazo.com/3d49f12ab438f4e132a8fd644e36841c
There are two website with the same category tree and category ids, but given category name in website scope is in its own language. 
As you can see the category name is written multiple times in the grid

If I use filters them it shows category names differently:
https://gyazo.com/32051a02fa112398ac76480a25514df1
Is this known bug? Do you have any fix for that?
Thank you in advance!!!!

**Comment by jayelkaake** [comment]
Hmm... yeah this is probably an issue that needs to be resolved. Myself or some other awesome developer should probably fix it.

**Comment by rspl1006** [comment]
Please review the code and let me know if anything will not work.


Thanks
Ashish

**Comment by jayelkaake** [comment]
Merged! Thanks @rspl1006

**Comment by melaxon** [comment]
solved! Thanks a lot!
