### ISSUE TITLE
Catalog Product * Blank Page ( no product grid).

### ISSUE THREAD

**Issue by HeartexceL** [jayelkaake/enhancedgrid#40]
Is this compatible with magento 1.9.2.4?  
if yes,
I've installed the extension successfully but the catalog product* page only displaying blank page and no product grid can be found.
I can only access the settings at the system configuration tab.

Kindly help. thanks

**Comment by Blackskyliner** [comment]
What resolved the issue? Why can no one state this when closing issues? I have now the same problem and would need to open almost exactly the same question/issue just with an higher version constraint...

**Comment by jayelkaake** [comment]
@Blackskyliner I think it was cache or a module confict.

**Comment by Blackskyliner** [comment]
Sadly not for me, as I already checked both before even looking into GitHub and I don't get it working. Thanks nonetheless 👍  - Maybe I'll open a new issue or just don't use the module. I'll see if something is really missing out in existing workflows to justify the correct integration of the module.

Sadly it doesn't even throw an error or anything. Pristine Magento installation of latest Magento 1.9.x.x with SQL Data from a 1.8.1.0 installation. Module handling via composer.

**Comment by jayelkaake** [comment]
Sorry I can't be of more help! Since it's working for others then its
almost definitely specific to your store. Short of you hiring me (
wellfounded.ca) to look at your store's code,  I don't have any other
suggestions.

**Comment by Blackskyliner** [comment]
Found the problem. I forgot to enable 'allow symlink' in the developer settings. As the composer installer symlinks the modules per default, I guess this was causing the module to fail.

**Comment by jayelkaake** [comment]
Yep - that'll do it! Any modules you're installing with modman/composer
you'll need to enable that option for it to work.​
