### ISSUE TITLE
Error @install extension

### ISSUE THREAD

**Issue by Insect2015** [jayelkaake/enhancedgrid#41]
hello guys,

I get a error after I have install the extension and click in the config page.

`Fatal error: Call to undefined method Mage_Eav_Model_Resource_Entity_Attribute_Collection::addVisibleFilter() in /data/web/public/app/code/community/TBT/Enhancedgrid/Model/System/Config/Source/Columns/Show.php on line 10`

**Comment by Bilal-H-Abdeen** [comment]
Did you install it from MagentoConnect website? If yes, try downloading the zip file from here (GitHub). Then, manually copy the folders to your Magento folder.

**Comment by jayelkaake** [comment]
+1 to what @Bilal-Abdeen  said.
