### ISSUE TITLE
I've got 404 when try to open catalog_product in admin

### ISSUE THREAD

**Issue by apaukraine** [jayelkaake/enhancedgrid#42]
When I openning admin/enhancedgrid/catalog_product/index I've got 404 error

**Comment by sergeifilippov** [comment]
Did you:

1. Clear Magento cache
2. Refreshed your ACL permissions by logging out of admin and logging back in.

?

**Comment by apaukraine** [comment]
Sure

**Comment by jayelkaake** [comment]
What @sergeifilippov said is correct. This is likely due to your ACL permissions.

**Comment by apaukraine** [comment]
I refreshed acl and clear cache.
