### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by tccoc** [jayelkaake/enhancedgrid#43]
Installed enhanced grid but it gives this error

Fatal error: Call to a member function toOptionArray() on boolean in /home/xxx/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Form.php on line 463

I also have HTTP ERROR 500  on the configuration page

I am using Magento 1.9.1.0

**Comment by jayelkaake** [comment]
That's because you have your Magento compiler enabled. You need to rebuild the compilation or turn it off before you install.
