### ISSUE TITLE
SSL Issue 

### ISSUE THREAD

**Issue by abhishekrocktechnolabs** [jayelkaake/enhancedgrid#56]
Hello,
          I am using that extension.
          On this file path:  enhancedgrid/app/code/community/TBT/Enhancedgrid/Block/Widget/Loyalty.php
          $url = 'https://www.wdca.ca/m';
          My website is running on https but its giving ssl error like certificate expired for https://www.wdca.ca/m  that url. Please check.
Thanks & Regards
Abhishek

**Comment by jayelkaake** [comment]
It may have not been updated but it is updated now. Anyways if you want to remove that just delete this line: https://github.com/jayelkaake/enhancedgrid/blob/master/app/design/adminhtml/default/default/template/tbt/enhancedgrid/catalog/product.phtml#L32

**Comment by abhishekrocktechnolabs** [comment]
Thanks
