### ISSUE TITLE
Issues after reinstallation

### ISSUE THREAD

**Issue by morgan** [jayelkaake/enhancedgrid#59]
Recently uninstalled and reinstalled through Magento Connect.

As a result, a couple oddities are now present:

- The menu item use to be first and carry an asterisk. Now it's third and does not.
- The old product manager is now first in the menu.
- When saving a product, it redirects the user back to the old product manager collection.

Flushed cache and recompiled.

Running Magento 1.8.1.0.

Any thoughts?

Thank you.

**Comment by jayelkaake** [comment]
This sounds like an extension conflict TBH. Any other extensions installed that are related?

**Comment by morgan** [comment]
@jayelkaake Thank you for the response! We had another extension that appears to have caused a conflict (although not necessarily related). Was able to get this sorted out. Thanks again!
