### ISSUE TITLE
Magento 1.9.0.1 compatibility

### ISSUE THREAD

**Issue by toroseduto** [jayelkaake/enhancedgrid#7]
Hi,

I have enhancegrid installed on magento 1.6. After I upgraded magento to 1.9.0.1 I have some issues with Manage Products grid:
- if I apply the filter enabled (status column), I see also disabled
- I can't see the thumbnail
- some products are enabled and visible on frontend, but on the product grid I see that are disable for all store view.

This module is very useful and I am grateful to anyone who can help me. Thanks.

Regards.

**Comment by jayelkaake** [comment]
Bit of a late response, but you still running into this issue? I haven't seen it anywhere else.
