### ISSUE TITLE
Release by git tag + register packagist

### ISSUE THREAD

**Issue by greenwellness** [jayelkaake/enhancedgrid#8]
Hi, have you considered publishing (registering) your package with composer repository *packagist*? It has a [big green button on the top right](https://packagist.org/packages/submit) which requires a one time registration by providing this repository URL. It then proceeds to look-up the current release version by means of your git tags (much prefered over branch->alias) and as such, even if this package is quite stable and doesn't get much work done, should still be set at tag `0.1.0` (that is if you adhere to the semantic versioning system I guess, and you should). This in order to distinguish it from any future work and prevent breaking on `composer update` when `dev-master` gets work done.

May I advice the excellent https://github.com/nvie/gitflow? A simple `git flow release start 0.1.0` followed by (optionally work done then) `git flow release finish 0.1.0` and a `git push --tags` should do the trick :)

**Comment by jayelkaake** [comment]
Super late response, but just a heads-up I've resumed maintenance of this repo and started using version tagging. If you still want it in composer I'll add it in, though many people are using modman which is now included.
